name: CI Enterprise

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install PNPM global
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        env: 
          BASE_URL: 'https://api2-qa-backend2.ploomeswin.dev'
        run: pnpm run test